In [27]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [28]:
ds =  pd.read_csv("data.csv")
ds

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [29]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

In [30]:
ds["gender"].unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [31]:
ds["smoking_history"].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [32]:
from sklearn.preprocessing import LabelEncoder

In [33]:
lbl = LabelEncoder()

In [34]:
ds["gender"] = lbl.fit_transform(ds["gender"])

In [35]:
ds["gender"].unique()

array([0, 1, 2])

In [36]:
ds["smoking_history"].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [37]:
smoking_map = {
    'never': 0,
    'former': 1,
    'not current': 2,
    'current': 3,
    'ever': 2,      # depends on your definition
    'No Info': -1
}

In [38]:
ds["smoking_history"] = ds["smoking_history"].map(smoking_map)

In [39]:
ds["smoking_history"].unique()

array([ 0, -1,  3,  1,  2])

In [40]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  int64
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  int64
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(6)
memory usage: 6.9 MB

In [41]:
ds.duplicated().value_counts()

False    96093
True      3907
Name: count, dtype: int64

In [42]:
ds.drop_duplicates(inplace=True)

In [43]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 96093 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               96093 non-null  int64
 1   age                  96093 non-null  float64
 2   hypertension         96093 non-null  int64
 3   heart_disease        96093 non-null  int64
 4   smoking_history      96093 non-null  int64
 5   bmi                  96093 non-null  float64
 6   HbA1c_level          96093 non-null  float64
 7   blood_glucose_level  96093 non-null  int64
 8   diabetes             96093 non-null  int64
dtypes: float64(3), int64(6)
memory usage: 7.3 MB

In [44]:
ds.duplicated().value_counts()

False    96093
Name: count, dtype: int64

In [45]:
ds.to_csv("clean_data.csv")

In [46]:
ds.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')

In [47]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [48]:
ds[['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level']] = sc.fit_transform(ds[['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level']])

In [49]:
X = ds[['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level']]

0       -0.843478
1       -0.843478
2        1.183742
3       -0.843478
4        1.183742
           ...
99994   -0.843478
99996   -0.843478
99997    1.183742
99998   -0.843478
99999   -0.843478
Name: gender, Length: 96093, dtype: float64

In [50]:
X = pd.DataFrame(data=X,columns=['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level'])
X

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
0,-0.843478,1.700916,-0.290137,4.847785,-0.198677,-0.314860,0.994389,0.043536
1,-0.843478,0.543495,-0.290137,-0.206280,-0.973902,-0.000216,0.994389,-1.423015
2,1.183742,-0.613925,-0.290137,-0.206280,-0.198677,-0.000216,0.155846,0.483502
3,-0.843478,-0.257796,-0.290137,-0.206280,2.126998,-0.571894,-0.496354,0.410174
4,1.183742,1.522851,3.446647,4.847785,2.126998,-1.060848,-0.682697,0.410174
...,...,...,...,...,...,...,...,...
99994,-0.843478,-0.257796,-0.290137,-0.206280,-0.973902,-0.402015,-0.682697,0.165749
99996,-0.843478,-1.771345,-0.290137,-0.206280,-0.973902,-1.470034,0.901218,-0.934165
99997,1.183742,1.077689,-0.290137,-0.206280,0.576548,0.075121,0.155846,0.410174
99998,-0.843478,-0.791990,-0.290137,-0.206280,-0.198677,1.196319,-1.428068,-0.934165
99999,-0.843478,0.677044,-0.290137,-0.206280,2.126998,-0.722569,0.994389,-1.178590

In [51]:
y = ds[["diabetes"]]
y

       diabetes
0             0
1             0
2             0
3             0
4             0
...         ...
99994         0
99996         0
99997         0
99998         0
99999         0

[96093 rows x 1 columns]

In [52]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [53]:
X_test

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
37538,1.183742,-1.415216,-0.290137,-0.20628,-0.973902,-1.589687,0.155846,0.165749
29382,-0.843478,-0.124247,-0.290137,-0.20628,-0.198677,-0.000216,0.621703,-1.423015
74980,1.183742,1.166722,-0.290137,-0.20628,0.576548,1.089960,1.180732,0.410174
27217,1.183742,-0.836506,-0.290137,-0.20628,-0.973902,-0.752113,-1.893926,0.165749
26083,1.183742,0.187366,-0.290137,-0.20628,2.126998,0.113529,0.994389,-1.423015
...,...,...,...,...,...,...,...,...
5788,-0.843478,-0.613925,-0.290137,-0.20628,2.126998,1.199274,0.621703,-0.200889
48992,-0.843478,-0.168763,-0.290137,-0.20628,-0.198677,0.444422,0.901218,1.510088
31775,-0.843478,0.276398,-0.290137,-0.20628,2.126998,0.654185,0.435361,0.410174
14981,-0.843478,1.478335,-0.290137,-0.20628,-0.198677,-0.124301,0.528532,1.510088
66448,-0.843478,-1.637797,-0.290137,-0.20628,-0.973902,-1.706386,0.901218,1.510088

In [54]:
from sklearn.linear_model import LogisticRegression

In [55]:
reg = LogisticRegression()

In [56]:
reg.fit(X_train,y_train)

LogisticRegression()

In [57]:
X_train

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
15800,1.183742,0.498979,3.446647,-0.206280,2.126998,-1.381402,-1.893926,0.410174
64550,-0.843478,0.009301,-0.290137,-0.206280,0.576548,0.320337,0.621703,0.483502
78299,1.183742,1.656399,-0.290137,-0.206280,-0.973902,-0.000216,0.249018,0.043536
83677,1.183742,1.389302,-0.290137,-0.206280,-0.973902,-0.000216,0.994389,-0.934165
98076,1.183742,1.077689,-0.290137,4.847785,0.576548,-0.304520,-0.496354,1.510088
...,...,...,...,...,...,...,...,...
6284,-0.843478,-1.326184,-0.290137,-0.206280,-0.973902,-0.998806,0.435361,0.532387
56206,1.183742,-1.415216,-0.290137,-0.206280,-0.973902,-2.108186,-0.496354,0.483502
79388,-0.843478,-0.346828,-0.290137,-0.206280,-0.973902,-0.659049,-0.496354,-1.178590
860,-0.843478,-0.213280,-0.290137,-0.206280,-0.198677,-0.348836,0.621703,0.483502
15910,1.183742,-0.257796,-0.290137,-0.206280,-0.973902,0.036714,-0.682697,0.043536

In [68]:
inputdata  = pd.DataFrame(data = [[1,53.0,1,0,3,17.97,3.5,155]],columns=['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level'] )
inputdata

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
0,1,53.0,1,0,3,17.97,3.5,155

In [69]:
reg.predict(sc.transform(inputdata))

array([0])

In [73]:
inputdata  = pd.DataFrame(data = [[1, 67.00, 0.00, 1, 2.00, 27.32, 6.50, 200.00]],columns=['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level'] )
inputdata
reg.predict(sc.transform(inputdata))

array([1])

In [75]:
y_pred = reg.predict(X_test)
y_pred

array([0, 0, 1, ..., 0, 0, 0])

In [76]:
y_pred = pd.DataFrame(data=y_pred,columns=['Result'])
y_pred

       Result
0           0
1           0
2           1
3           0
4           0
...       ...
19214       0
19215       0
19216       0
19217       0
19218       0

[19219 rows x 1 columns]

In [77]:
y_pred["Result"].value_counts()

Result
0    17972
1     1247
Name: count, dtype: int64

In [78]:
result =  pd.concat((y_test.reset_index(drop=True),y_pred.reset_index(drop=True)),axis=1)
result

       diabetes  Result
0             0       0
1             0       0
2             1       1
3             0       0
4             0       0
...         ...     ...
19214         0       0
19215         0       0
19216         0       0
19217         0       0
19218         0       0

[19219 rows x 2 columns]

In [79]:
from  sklearn.metrics import accuracy_score
score = accuracy_score(result["diabetes"],result["Result"])
score*100

95.72818564961757

In [80]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(result["diabetes"],result["Result"])
cm

array([[17329,   178],
       [  643,  1069]])

In [75]:
if result==1:
    print("Person in diabetic")
else:
     print("Person not in diabetic")

Person not in diabetic

In [82]:
import pickle as pkl

In [84]:
pkl.dump(reg,open("CPP.pkl","wb+"))

In [85]:
pkl.dump(sc,open("sc.pkl","wb+"))